services:
  authjs-docker-test:
    build: .
    environment:
      - TEST_KEYCLOAK_USERNAME=waiuser
      - TEST_KEYCLOAK_PASSWORD=waipass
      # - AUTH_KEYCLOAK_ID
      # - AUTH_KEYCLOAK_SECRET
      # - AUTH_KEYCLOAK_ISSUER
      # - AUTH_SECRET=MohY0/2zSQw/psWEnejC2ka3Al0oifvY4YjOkUaFfnI=
      - AUTH_SECRET=/SnU2GJMWdylkc2BhxjOtYtqbIYpZD5baV39GLLAglo=
      - AUTH_URL=http://localhost:3000/auth
    ports:
      - "3000:3000"
